const { UUID, UUIDV4, STRING, INTEGER } = require('sequelize');
const Sequalize = require('sequelize');
const db = require('./conn.js');
const Team = require('./Team');
// const Division = require('./Division');

const syncAndSeed = async () => {
  try {
    await db.sync({ force: true });

    //////////// AFC WEST //////////////////////////////
    Team.create({
      name: 'CHIEFS',
      division: 'AFC WEST',
      seasons: [
        {
          year: 2018,
          wins: 12,
          losses: 4,
          totalOffense: 6810,
          totPassYds: 4955,
          passYdsGame: 309.7,
          totRushYds: 1855,
          rushYdsGame: 115.9,
          defRank: 31,
        },
        {
          year: 2019,
          wins: 12,
          losses: 4,
          totalOffense: 6067,
          totPassYds: 4498,
          passYdsGame: 281.1,
          totRushYds: 1569,
          rushYdsGame: 98.1,
          defRank: 17,
        },
        {
          year: 2020,
          wins: 14,
          losses: 2,
          totalOffense: 6653,
          totPassYds: 4854,
          passYdsGame: 303.4,
          totRushYds: 1799,
          rushYdsGame: 112.4,
          defRank: 16,
        },
        {
          year: 2021,
          wins: 12,
          losses: 5,
          totalOffense: 6746,
          totPassYds: 4791,
          passYdsGame: 281.8,
          totRushYds: 1955,
          rushYdsGame: 115.0,
          defRank: 27,
        },
        {
          year: 2022,
          wins: 14,
          losses: 3,
          totalOffense: 7032,
          totPassYds: 5062,
          passYdsGame: 297.4,
          totRushYds: 1970,
          rushYdsGame: 115.0,
          defRank: 8,
        },
      ],
      coaching: 5,
    });
    Team.create({
      name: 'CHARGERS',
      division: 'AFC WEST',
      seasons: [
        {
          year: 2018,
          wins: 12,
          losses: 4,
          totalOffense: 5962,
          totPassYds: 4089,
          passYdsGame: 255.6,
          totRushYds: 1873,
          rushYdsGame: 117.1,
          defRank: 9,
        },
        {
          year: 2019,
          wins: 5,
          losses: 11,
          totalOffense: 5879,
          totPassYds: 4426,
          passYdsGame: 276.6,
          totRushYds: 1453,
          rushYdsGame: 90.8,
          defRank: 6,
        },
        {
          year: 2020,
          wins: 7,
          losses: 9,
          totalOffense: 6113,
          totPassYds: 4329,
          passYdsGame: 270.6,
          totRushYds: 1784,
          rushYdsGame: 111.4,
          defRank: 10,
        },
        {
          year: 2021,
          wins: 9,
          losses: 8,
          totalOffense: 6634,
          totPassYds: 4800,
          passYdsGame: 282.4,
          totRushYds: 1834,
          rushYdsGame: 107.9,
          defRank: 23,
        },
        {
          year: 2022,
          wins: 10,
          losses: 7,
          totalOffense: 6108,
          totPassYds: 4584,
          passYdsGame: 269.6,
          totRushYds: 1524,
          rushYdsGame: 89.6,
          defRank: 20,
        },
      ],
      coaching: 2,
    });
    Team.create({
      name: 'RAIDERS',
      division: 'AFC WEST',
      seasons: [
        {
          year: 2018,
          wins: 4,
          losses: 12,
          totalOffense: 5379,
          totPassYds: 3751,
          passYdsGame: 234.4,
          totRushYds: 1628,
          rushYdsGame: 101.8,
          defRank: 26,
        },
        {
          year: 2019,
          wins: 7,
          losses: 9,
          totalOffense: 5819,
          totPassYds: 3926,
          passYdsGame: 245.4,
          totRushYds: 1893,
          rushYdsGame: 118.3,
          defRank: 19,
        },
        {
          year: 2020,
          wins: 8,
          losses: 8,
          totalOffense: 6133,
          totPassYds: 4217,
          passYdsGame: 263.6,
          totRushYds: 1916,
          rushYdsGame: 119.8,
          defRank: 25,
        },
        {
          year: 2021,
          wins: 10,
          losses: 7,
          totalOffense: 6184,
          totPassYds: 4567,
          passYdsGame: 268.6,
          totRushYds: 1617,
          rushYdsGame: 95.1,
          defRank: 14,
        },
        {
          year: 2022,
          wins: 6,
          losses: 11,
          totalOffense: 5993,
          totPassYds: 3934,
          passYdsGame: 231.4,
          totRushYds: 2059,
          rushYdsGame: 121.1,
          defRank: 28,
        },
      ],
      coaching: 2,
    });
    Team.create({
      name: 'BRONCOS',
      division: 'AFC WEST',
      seasons: [
        {
          year: 2018,
          wins: 6,
          losses: 10,
          totalOffense: 5602,
          totPassYds: 3695,
          passYdsGame: 230.9,
          totRushYds: 1907,
          rushYdsGame: 119.2,
          defRank: 22,
        },
        {
          year: 2019,
          wins: 7,
          losses: 9,
          totalOffense: 4777,
          totPassYds: 3115,
          passYdsGame: 194.7,
          totRushYds: 1662,
          rushYdsGame: 103.9,
          defRank: 12,
        },
        {
          year: 2020,
          wins: 5,
          losses: 11,
          totalOffense: 5369,
          totPassYds: 3451,
          passYdsGame: 215.7,
          totRushYds: 1918,
          rushYdsGame: 119.9,
          defRank: 21,
        },
        {
          year: 2021,
          wins: 7,
          losses: 10,
          totalOffense: 5618,
          totPassYds: 3593,
          passYdsGame: 211.4,
          totRushYds: 2025,
          rushYdsGame: 119.1,
          defRank: 8,
        },
        {
          year: 2022,
          wins: 5,
          losses: 12,
          totalOffense: 5499,
          totPassYds: 3626,
          passYdsGame: 213.3,
          totRushYds: 1873,
          rushYdsGame: 110.2,
          defRank: 7,
        },
      ],
      coaching: 1,
    });
    Team.create({
      name: 'BILLS',
      division: 'AFC EAST',
      seasons: [
        {
          year: 2018,
          wins: 6,
          losses: 10,
          totalOffense: 4778,
          totPassYds: 2994,
          passYdsGame: 174.6,
          totRushYds: 1984,
          rushYdsGame: 124.0,
          defRank: 2,
        },
        {
          year: 2019,
          wins: 10,
          losses: 6,
          totalOffense: 5283,
          totPassYds: 3229,
          passYdsGame: 201.8,
          totRushYds: 2054,
          rushYdsGame: 128.4,
          defRank: 3,
        },
        {
          year: 2020,
          wins: 13,
          losses: 3,
          totalOffense: 6343,
          totPassYds: 4620,
          passYdsGame: 288.8,
          totRushYds: 1723,
          rushYdsGame: 107.7,
          defRank: 14,
        },
        {
          year: 2021,
          wins: 11,
          losses: 6,
          totalOffense: 6493,
          totPassYds: 4284,
          passYdsGame: 252.0,
          totRushYds: 2209,
          rushYdsGame: 129.9,
          defRank: 1,
        },
        {
          year: 2022,
          wins: 13,
          losses: 3,
          totalOffense: 6361,
          totPassYds: 4129,
          passYdsGame: 258.1,
          totRushYds: 2232,
          rushYdsGame: 139.5,
          defRank: 6,
        },
      ],
      coaching: 3,
    });
    Team.create({
      name: 'JETS',
      division: 'AFC EAST',
      seasons: [
        {
          year: 2018,
          wins: 4,
          losses: 12,
          totalOffense: 4787,
          totPassYds: 3165,
          passYdsGame: 197.8,
          totRushYds: 1622,
          rushYdsGame: 101.4,
          defRank: 25,
        },
        {
          year: 2019,
          wins: 7,
          losses: 9,
          totalOffense: 4368,
          totPassYds: 3111,
          passYdsGame: 194.4,
          totRushYds: 1257,
          rushYdsGame: 78.6,
          defRank: 7,
        },
        {
          year: 2020,
          wins: 2,
          losses: 14,
          totalOffense: 4479,
          totPassYds: 2796,
          passYdsGame: 174.8,
          totRushYds: 1683,
          rushYdsGame: 105.2,
          defRank: 24,
        },
        {
          year: 2021,
          wins: 4,
          losses: 13,
          totalOffense: 5208,
          totPassYds: 3541,
          passYdsGame: 208.3,
          totRushYds: 1667,
          rushYdsGame: 98.1,
          defRank: 31,
        },
        {
          year: 2022,
          wins: 7,
          losses: 10,
          totalOffense: 5409,
          totPassYds: 3723,
          passYdsGame: 219.0,
          totRushYds: 1686,
          rushYdsGame: 99.2,
          defRank: 4,
        },
      ],
      coaching: 3,
    });
    Team.create({
      name: 'PATRIOTS',
      division: 'AFC EAST',
      seasons: [
        {
          year: 2018,
          wins: 11,
          losses: 5,
          totalOffense: 6295,
          totPassYds: 4258,
          passYdsGame: 266.1,
          totRushYds: 2037,
          rushYdsGame: 127.3,
          defRank: 21,
        },
        {
          year: 2019,
          wins: 12,
          losses: 4,
          totalOffense: 5664,
          totPassYds: 3961,
          passYdsGame: 247.6,
          totRushYds: 1703,
          rushYdsGame: 106.4,
          defRank: 1,
        },
        {
          year: 2020,
          wins: 7,
          losses: 9,
          totalOffense: 5236,
          totPassYds: 2890,
          passYdsGame: 180.6,
          totRushYds: 2346,
          rushYdsGame: 146.6,
          defRank: 15,
        },
        {
          year: 2021,
          wins: 10,
          losses: 7,
          totalOffense: 6008,
          totPassYds: 3857,
          passYdsGame: 226.9,
          totRushYds: 2151,
          rushYdsGame: 126.5,
          defRank: 4,
        },
        {
          year: 2022,
          wins: 8,
          losses: 9,
          totalOffense: 5348,
          totPassYds: 3536,
          passYdsGame: 208,
          totRushYds: 1812,
          rushYdsGame: 106.6,
          defRank: 8,
        },
      ],
      coaching: 5,
    });
    Team.create({
      name: 'DOLPHINS',
      division: 'AFC EAST',
      seasons: [
        {
          year: 2018,
          wins: 7,
          losses: 9,
          totalOffense: 4638,
          totPassYds: 2900,
          passYdsGame: 181.3,
          totRushYds: 1738,
          rushYdsGame: 108.6,
          defRank: 29,
        },
        {
          year: 2019,
          wins: 5,
          losses: 11,
          totalOffense: 4960,
          totPassYds: 3804,
          passYdsGame: 237.8,
          totRushYds: 1156,
          rushYdsGame: 72.3,
          defRank: 30,
        },
        {
          year: 2020,
          wins: 10,
          losses: 6,
          totalOffense: 5424,
          totPassYds: 3736,
          passYdsGame: 233.5,
          totRushYds: 1688,
          rushYdsGame: 105.5,
          defRank: 20,
        },
        {
          year: 2021,
          wins: 9,
          losses: 8,
          totalOffense: 5219,
          totPassYds: 3651,
          passYdsGame: 214.8,
          totRushYds: 1568,
          rushYdsGame: 92.2,
          defRank: 15,
        },
        {
          year: 2022,
          wins: 9,
          losses: 8,
          totalOffense: 6197,
          totPassYds: 4511,
          passYdsGame: 265.4,
          totRushYds: 1686,
          rushYdsGame: 99.2,
          defRank: 18,
        },
      ],
      coaching: 1,
    });
  } catch (error) {
    console.log(error);
  }
};

module.exports = {
  db,
  Team,
  // Division,
  syncAndSeed,
};
